package com.vzw.edr.selfProv.utils;

public class VendorXml {

	/* Request
	 <?xml version="1.0" encoding="UTF-8"?>
	<!--Change Order-->
	<SPVReqRec xmlns="http://www.vzw.com/namespaces/spv" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vzw.com/namespaces/spv SelfProvisioningVendor1.2.xsd" ReqType="i">
		<req_event_id>232</req_event_id>
		<event_date>2001-12-17T09:30:47</event_date>
		<mdn>2147483647</mdn>
		<min>2147483647</min>
		<vendor_id>299005</vendor_id>
		<service_id action="add">RBT</service_id>
		<channel_id>99</channel_id>
		<content_id action="add" default="true">432</content_id>
		<content_id action="add" default="false">12</content_id>
	</SPVReqRec>
	
	 */

	/* Response
	 <?XML version="1.0" encoding="UTF-8" ?> 
	- <!-- 
	Sample XML file generated by XMLSPY v5 rel. 3 U (HTTP://www.XMLspy.com)
	--> 
	- <SPVRespRec XMLns="HTTP://www.vzw.com/namespaces/spv" XMLns:xsi="HTTP://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="HTTP://www.vzw.com/namespaces/spv SelfProvisioningVendor1.0.xsd">
	<req_event_id>1</req_event_id> 
	<resp_event_id>2</resp_event_id> 
	<resp_code>0</resp_code> 
	<resp_description>OK</resp_description> 
	<SPVRespRec>
	 */

	public static final String reqStHeaderXml =
		"<?xml version=\"1.0\" encoding=\"UTF-8\" ?>"
			+ "<SPVReqRec xmlns=\"http://vzw.com/namespaces/spv\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.vzw.com/namespaces/spv SelfProvisioningVendor1.0.xsd\" ";
	public static final String sfo = "<";
	public static final String efo = ">";
	public static final String req_event_idSfo = "<req_event_id>";
	public static final String req_event_idEfo = "</req_event_id>";
	public static final String event_dateSfo = "<event_date>";
	public static final String event_dateEfo = "</event_date>";
	public static final String mdnSfo = "<mdn>";
	public static final String mdnEfo = "</mdn>";
	public static final String minSfo = "<min>";
	public static final String minEfo = "</min>";
	public static final String prepay_indSfo = "<prepay_ind>";
	public static final String prepay_indEfo = "</prepay_ind>";
	public static final String vendor_idSfo = "<vendor_id>";
	public static final String vendor_idEfo = "</vendor_id>";
	public static final String service_idSfo = "<service_id>";
	public static final String service_idEfo = "</service_id>";
	public static final String channel_idSfo = "<channel_id>";
	public static final String channel_idEfo = "</channel_id>";
	public static final String content_idSfo = "<content_id ";
	public static final String content_idEfo = "</content_id>";
	public static final String actionAttr = " action=";
	public static final String serviceAttr = " service_id=";
	public static final String statusAttr = " status=";
	public static final String defaultAttr = " default=";
	public static final String reqTypeAttr = " ReqType=\"";
	public static final String numPurchasesAttr = " numPurchases=";
	public static final String purchasesLimitAttr = " purchaseLimit=";
	public static final String reqFooterXml = "</SPVReqRec>";

	public static final String respHeaderXml =
		"<?xml version=\"1.0\" encoding=\"UTF-8\" ?>"
			+ "<SPVReqRec xmlns=\"http://vzw.com/namespaces/spv\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.vzw.com/namespaces/spv SelfProvisioningVendor1.0.xsd\">";

	public static final String respFooterXml = "</SPVReqRec>";
}
