<?xml version="1.0" encoding="ISO-8859-1" ?>
<%@ page language="java" import="com.vzw.selfProvisioning.mobileWeb.*, com.vzw.selfProvisioning.utils.*, com.vzw.edr.selfProv.utils.*, org.apache.log4j.*" %>
<%!
	static Logger L = Logger.getLogger(SPProps.feLoggerBase + ".discWarrantiesTC_jsp");		
%>
<%
	String imgBaseUrl = Util.getContextURL(request);		
%>

<document>
	<para>
		<logoImg><%= imgBaseUrl %>images/vzwLogo.jpg</logoImg>				
		<paraValue>DISCLAIMER OF WARRANTIES. YOU ASSUME ALL RESPONSIBILITY AND RISK FOR THE USE OF 
		 THE SERVICES AND THE INTERNET GENERALLY. THE USE OF THE INFORMATION, PRODUCTS, AND/OR 
		 SERVICES PROVIDED ON OR AVAILABLE THROUGH THE SERVICES ARE PROVIDED ON AN "AS IS" AND 
		 "AS AVAILABLE" BASIS, WITHOUT WARRANTIES OF ANY KIND. NEITHER VERIZON WIRELESS NOR ITS 
		 AFFILIATES WARRANT THAT THE INFORMATION, PRODUCTS, PROCESSES, AND/OR SERVICES AVAILABLE 
		 THROUGH THE SERVICES WILL BE UN-INTERRUPTIBLE, ACCURATE, COMPLETE, USEFUL, FUNCTIONAL OR 
		 ERROR FREE, OR THAT ANY INFORMATION, SOFTWARE OR OTHER MATERIAL ACCESSIBLE THROUGH THE 
		 SERVICES IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE HAVE NO CONTROL OVER OR 
		 RESPONSIBILITY FOR CONTENT ON THIRD PARTY WEBSITES. WE CANNOT BE HELD LIABLE FOR ANY 
		 DAMAGES OR INJURY ARISING FROM CONTENT ON SUCH THIRD PARTY WEBSITES.</paraValue>
		<tcLink><%=response.encodeURL(SPProps.termsAndConditionsUrl)%></tcLink>
	</para>
</document>
